### ISSUE TITLE
To add ESLint.

### ISSUE THREAD

**Issue by ghost** [xSequential/Exercise-Template-Node-React-Mongo#2]
If you add eslint config from airbnb (https://www.npmjs.com/package/eslint-config-airbnb-base), you'll find some problems in your interview--complete project.

**Comment by tripndots** [comment]
@serge-nikitin , I do not find this to be an "issue"; however, since eslint with the airbnb config is such a popular way of writing js. I will consider reformatted with this because it may be necessary to have a more globally accepted convention of writing js to let the developer feel more comfortable working within my template. 

Everything that eslint picked up is formatting errors. Correct me if I'm wrong. Thank you for your input @serge-nikitin !

**Comment by ghost** [comment]
For example ESLint from airbnb will find a such mistake in AddProperty.js:

```
AddProperty.PropTypes = {
    handleAdd: React.PropTypes.func
}

```
https://facebook.github.io/react/docs/typechecking-with-proptypes.html -- they say that you should type: `AddProperty.propTypes = `

So I really recommend you to try eslint-config-airbnb-base, you will have a different language, much better.

**Comment by tripndots** [comment]
@serge-nikitin  Oh yes, good call! That is definitely something that should be fixed.

Thank you, I have not closed this out and will work on this. This is simply a good practice that should be applied.

**Comment by tripndots** [comment]
I have linted with esLint standard. https://standardjs.com/

Thank your for the submission.
